logging:
   level:
     com.atomist.spring.agent: DEBUG

atomist:
  enabled: true
  debug: true
  url: 'https://webhook.atomist.com/atomist/application/teams/A5Z64H1FA'
  environment:
      domain: '${ATOMIST_ENVIRONMENT:${vcap.application.space_name:development}}'
      pod: '${HOSTNAME:${random.value}}'
